config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "splash#index"
  resources :groups, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
    resources :operations, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  end
 
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :operations, dependent: :destroy

  validates :icon, :name, presence: true

  def timelapse
    start_time = created_at
    end_time = Time.now
    TimeDifference.between(start_time, end_time).humanize
  end

  def self.created_by_current_user(current_user)
    where(user_id: current_user.id).order(created_at: :desc)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /groups or /groups.json
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new

    @icons = [
      { 'name' => 'Choose a category icon',
        'source' => '/icons/Accomodation.png' },
      { 'name' => 'Food',
        'source' => '/icons/Accomodation.png' },
      { 'name' => 'Home appliances',
        'source' => '/icons/appliances.png' },
      { 'name' => 'Clothing',
        'source' => '/icons/clothing.png' },
      { 'name' => 'Children',
        'source' => '/icons/kids.png' },
      { 'name' => 'Transportation',
        'source' => '/icons/travels.png' },
      { 'name' => 'Others',
        'source' => '/icons/others.png' }
    ]
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.new(group_params)
    # @group.user = @user

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class= "form">
  <%= form_with(model: group) do |form| %>
    <% if group.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
    <%= form.label :icon, style: "display: block" %>
      <div class= "dropdown">
        <%= form.select :icon, @icons.map { |icon| [icon['name'], icon['source']] } %>
      </div>
    </div>

    <div class= "group-name">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div class="submit">
      <%= form.submit %>
    </div>
  <% end %>

</div>

app/views/groups/_group.html.erb
<div id="group">
  <div class= "image-icon">
    <img src=<%= group.icon %> class= "group-img">
    <h3>
      <%= group.name %>
    </h3>
  </div>


  <div class="category-total-amount">
    <Span>
        $<%= group.operations.inject(0) { |sum, e| sum += e.amount  }%> 
    </Span>
  </div>

</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>
<div class= "header">
  <%= link_to root_path do %><%= image_tag "back.png", class:"back"%><%end%>
  <h2>Categories</h2>
  <%= button_to destroy_user_session_path, method: :delete, class:"off" do %> 
    <%= image_tag "off.png", class:"off"%>
  <%end%>
</div>


<div id="groups">
  <%if @groups.any?%>
    <% @groups.each do |group| %>
      <%if can? :manage, group%>
        <div class= "group">
          <%= link_to group_operations_path(group), id: "group-container" do %>
            <%= render group %>
          <%end%>
          <div class= "group-footers">
            <div>
              <small class= "timelapse"><%= group.timelapse%> ago</small>
            </div>
            <div class= "show-delete">
              <%= link_to "View", group %>
              <%= button_to "Delete", group, method: :delete, class: "delete" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <%else%>
      <h3 style="text-align: center">Welcome! You have not added any Categories yet</h3>
  <%end%>

</div>

<div class= "new-group">
  <div class= "new-group-btn"><%= link_to "Add new category", new_group_path %></div>
</div>

app/views/groups/new.html.erb
<div class= "new-group-wrapper">
  <h1>New Category</h1>

  <%= render "form", group: @group %>

  <br>

  <div>
    <%= link_to "Back to groups", groups_path %>
  </div>
</div>

app/views/groups/show.html.erb
<div class= "group">
  <p style="color: green"><%= notice %></p>

  <%= render @group %>

  <div class= "show-links">
    <%= link_to "Edit", edit_group_path(@group) %>

    <%= button_to "Delete", @group, method: :delete %>
    
    <%= link_to "Go back", groups_path %>
    
  </div>
</div>