config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "splash#index"
  resources :groups, only: [:index, :create, :new, :show, :edit, :update, :destroy] do
    resources :operations, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  end
 
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :author, class_name: 'User', dependent: :destroy, foreign_key: 'author_id'
  has_and_belongs_to_many :groups, dependent: :destroy

  validates :name, :amount, presence: true

  def timelapse
    start_time = created_at
    end_time = Time.now

    TimeDifference.between(start_time, end_time).humanize
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[show edit update destroy new create]
  before_action :authenticate_user!

  def index
    @group = Group.find(params[:group_id])
    @operations = @group.operations.order(created_at: :desc)
  end

  # GET /operations/1 or /operations/1.json
  def show; end

  # GET /operations/new
  def new
    @operation = Operation.new
    @operations = Operation.all
    @groups = Group.created_by_current_user(current_user)
  end

  def edit; end

  def create
    params = operation_params
    @operation = Operation.new(name: params[:name], amount: params[:amount])
    @operation.author = current_user
    @group_ids = params[:group_ids]
    if @group_ids.present?
      @group_ids.each do |id|
        @group = Group.find(id) unless id == ''
        @operation.groups.push(@group) unless @group.nil?
      end
    end

    respond_to do |format|
      if @operation.save
        format.html do
          redirect_to group_operations_url(@operation.groups.first.id), notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to group_operations_url(@operation), notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html do
        redirect_to group_operations_url(@operation.groups.first.id), notice: 'Transaction was successfully deleted.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_operation
    # @group = groups.operations.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def operation_params
    params.require(:operation).permit(:name, :amount, group_ids: [])
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<div class= "form">
  <%= form_with model: @operation, url: group_operations_path, method: :post do |form| %>
    <% if operation.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

        <ul>
          <% operation.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class= "group-name">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div class= "group-name">
      <%= form.label :amount, style: "display: block" %>
      <%= form.number_field :amount %>
    </div>
    <p>Select category to add new transaction</p>
    <div class= "checkbox">
      <%if @groups%>
          <%= form.label :groups %>
          <%= form.collection_check_boxes(:group_ids, @groups, :id, :name) do |b| %>
              <div class="inputs">
              <%= b.check_box + b.label %>
              </div>
          <% end %>
      <%end%>
    </div>

    <div class="submit-btn">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">
  <div id="group">
    <p>
      <%= operation.name %>
    </p>

    <p>
      $<%= operation.amount %>
    </p>
  </div>
  <div class= "group-footers">
    <small class= "timelapse"><%= operation.timelapse%> ago</small>
    <div>
    <%= button_to "Delete", @operation, method: :delete, class: "delete" %>
    </div>

  </div>
</div>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Show this operation", @operation %> |
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/index.html.erb
<div id= "">
  <p style="color: green"><%= notice %></p>

  <div class= "header">
    <%= link_to groups_path do %><%= image_tag "back.png", class:"back"%><%end%>
    <h2>Transactions</h2>
    <%= button_to destroy_user_session_path, method: :delete, class: "off" do %> 
      <%= image_tag "off.png", class:"off"%>
    <%end%>
  </div>

  <div class= "total-transactions">
    <small class= "total-transactions">
    <strong>Total Transactions:</strong>
    $<%= @operations.inject(0) { |sum, t| sum += t.amount  }%> 
    </small>
  </div>

  <div id="operations">
      <% if @operations.any? %>
        <div class= "group">
          <% @operations.each do |operation| %>
            <%= render operation %> 
          <% end %>
        </div>
      <% else %>
        <h2 style="text-align: center">No Transactions found, Add a new operation.</h2>
      <% end %>
  </div>
  <div class= "new-group">
    <div class= "new-group-btn"><%= link_to "New operation", new_group_operation_path(@operations) %>
    </div>
  </div>
</div>

app/views/operations/new.html.erb
<div class= "new-operation-wrapper">
  <h1>New operation</h1>

  <%= render "form", operation: @operation %>

  <br>
</div>

app/views/operations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @operation %>

<div>
  <%= link_to "Edit this operation", edit_operation_path(@operation) %> |
  <%= link_to "Back to operations", operations_path %>

  <%= button_to "Destroy this operation", @operation, method: :delete %>
</div>